# Generated by Django 2.1.3 on 2018-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('func_id', models.AutoField(primary_key=True, serialize=False)),
                ('func_nome', models.CharField(max_length=30)),
                ('func_funcao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OportunidadesRecente',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('op_nome', models.CharField(max_length=30)),
                ('op_descricao', models.TextField()),
                ('op_data', models.DateField()),
                ('op_dapartamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdensServico',
            fields=[
                ('os_numero', models.AutoField(primary_key=True, serialize=False)),
                ('os_nome', models.CharField(max_length=30)),
                ('os_recursos', models.PositiveIntegerField()),
                ('os_descricao', models.TextField()),
            ],
        ),
    ]
