# Generated by Django 2.1.3 on 2018-11-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordensDeServico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensservico',
            name='os_numero',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
