# Generated by Django 2.1.3 on 2018-12-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordensDeServico', '0003_auto_20181129_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='func_status',
            field=models.BooleanField(default=False),
        ),
    ]
